
services:
  api:
    build: .
    container_name: cultureia-auth-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cultureia_db
      - SECRET_KEY=cultureia_db
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    networks:
      - cultureia-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: cultureia-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cultureia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cultureia-network
    restart: unless-stopped

networks:
  cultureia-network:
    driver: bridge

volumes:
  postgres_data: